#!/usr/bin/env bash
# This script reads the /etc/passwd file and formats the output into a story with user information.
while IFS=: read -r username _ userid group _ _ home shell; do
	  echo "The user $username is part of the $group gang, lives in $home and rides $shell. $userid's place is protected by the passcode x, more info about the user here: $username"
  done < /etc/passwd
