#!/usr/bin/env bash
# This script parses /etc/passwd and formats user information
IFS=":"; while read -r username _ uid gid _ home shell _; do echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode x, more info about the user here: $username"; done < /etc/passwd
