#!/usr/bin/env bash
# This script reads /etc/passwd and formats user data

while IFS=":" read -r USERNAME _ GROUP_ID _ HOME_DIRECTORY _ _ COMMAND; do
	    echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND. $GROUP_ID's place is protected by the passcode x, more info about the user here: $USERNAME"
    done < /etc/passwd
    
