#!/usr/bin/env bash
# This script groups the Apache log data by IP and HTTP status code, counts the occurrences, and sorts them.

awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr | awk '{printf "%6d %s %s\n", $1, $2, $3}'
