#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, and displays the occurrence count, sorted from greatest to lowest.
awk '{print $1, $9}' /var/log/apache2/access.log | sort | uniq -c | sort -nr | awk '{print $1, $2, $3}'
