#!/usr/bin/env bash
# Create a PID file, print messages indefinitely, and handle different signals

echo $$ > /var/run/myscript.pid
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid; exit' SIGQUIT SIGTERM
while true; do echo "To infinity and beyond"; sleep 2; done
