#!/usr/bin/env bash
# Display the PID and command name of processes containing 'bash'

for pid in /proc/[0-9]*; do
	  cmd=$(cat "$pid/cmdline" 2>/dev/null)
	    if [[ $cmd == *bash* ]]; then
		        echo "$(basename $pid) $cmd"
			  fi
		  done
